spring.datasource.url=jdbc:mysql://avnadmin:AVNS_ZduNkDhRkL46lZvuh3i@mysql-31229e96-calranderr-ffda.a.aivencloud.com:21277/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8085
